package org.Password_Generator;

/**
 * Evaluates a given password's strength.
 * Uses the <b>Password Entropy Formula</b> to calculate the password's Strength.
 * <br><br>
 */
public class StrengthChecker {
    /**
     * Computes the entropy of the password generated by the password generator.
     * Using the {@code Password Entropy Formula} or {@code (passwordLength)*(Log2(charPoolSize))}.
     *
     * @param config the configuration of the password
     * @param passwordLength the length of the password
     * @return the bit entropy of the password generated
     */
    public static double getGeneratorEntropy(Configurator config, int passwordLength) {
        int charPoolSize = 0;

        final int DIGIT_POOL_SIZE = 10;
        final int SPECIAL_CHAR_POOL_SIZE = 32;
        final int MIXED_CASE_POOL_SIZE = 52;
        final int LOWER_CASE_POOL_SIZE = 26;


        if (config.hasDigit()) charPoolSize += DIGIT_POOL_SIZE;
        if (config.hasSpecialChar()) charPoolSize += SPECIAL_CHAR_POOL_SIZE;
        if (config.hasMixedCase()) charPoolSize += MIXED_CASE_POOL_SIZE;
        else charPoolSize += LOWER_CASE_POOL_SIZE;

        return passwordLength * log2(charPoolSize);
    }

    /**
     *  Computes the entropy of the password entered in the sign-up page.
     *  Using the {@code Password Entropy Formula} or {@code (passwordLength)*(Log2(charPoolSize))}.
     *
     * @param config the configuration of the password
     * @param passwordLength the length of the password
     * @return the bit entropy of the password generated for the sign-up page
     */
    public static double getSignUpEntropy(Configurator config, int passwordLength) {
        int charPoolSize = 0;

        final int DIGIT_POOL_SIZE = 10;
        final int SPECIAL_CHAR_POOL_SIZE = 32;
        final int UPPER_CASE_POOL_SIZE = 26;
        final int LOWER_CASE_POOL_SIZE = 26;


        if (config.hasDigit()) charPoolSize += DIGIT_POOL_SIZE;
        if (config.hasSpecialChar()) charPoolSize += SPECIAL_CHAR_POOL_SIZE;
        if (config.hasUpperCase()) charPoolSize += UPPER_CASE_POOL_SIZE;
        if (config.hasLowerCase()) charPoolSize += LOWER_CASE_POOL_SIZE;

        return passwordLength * log2(charPoolSize);
    }

    /**
     * Interprets the <b>Descriptive Strength</b> of the password based on the thresholds.
     * @param initialEntropy the numerical initialEntropy of the password from 0 to 1
     * @return a descriptive interpretation of the initialEntropy of the password generated based on the threshold
     */
    public static String checkGeneratedStrength(double initialEntropy) {
        final double VERY_STRONG_THRESHOLD = 0.75;
        final double STRONG_THRESHOLD = 0.50;
        final double MEDIUM_THRESHOLD = 0.25;

        double normalizedStrength = getNormalizedValue(initialEntropy);

        return switch (normalizedStrength) {
            case double v when v >= VERY_STRONG_THRESHOLD -> "VERY STRONG";
            case double v when v >= STRONG_THRESHOLD -> "STRONG";
            case double v when v >= MEDIUM_THRESHOLD -> "MEDIUM";
            default -> "WEAK";
        };
    }

    /**
     * Checks the strength of the master password, but instead of using the {@code Normalization Formula}
     * and {@code getNormalizedValue()} it uses a standardized threshold for entropy.
     *
     * @param entropyBits the bit entropy of the master password
     * @return a percentage of the strength of the master password
     */
    public static double checkManualEntryStrength(double entropyBits) {
        if (entropyBits >= 128) return (double) 100 /100;
        else if (entropyBits >= 60) return (double) 75/100;
        else if (entropyBits >= 36) return (double) 50/100;
        else if (entropyBits >= 28) return (double) 25/100;
        else return (double) 0/100;
    }

    public static String displayManualEntryStrength(double manualEntryStrength) {
        if (manualEntryStrength >= 1) return "VERY STRONG";
        else if (manualEntryStrength >= 0.75) return "STRONG";
        else if (manualEntryStrength >= 0.50) return "MEDIUM";
        else if (manualEntryStrength >= 0.25) return "WEAK";
        else return "VERY WEAK";
    }

    /**
     * Calculates the base-2 logarithm for a positive integer.
     * Returns 0 for an input of 1. Undefined for n <= 0.
     */
    private static double log2(int n) {
        if (n <= 0) {
            n = 1; //prevents n being equal to 0.
        }
        return Math.log(n) / Math.log(2);
    }

    /**
     * Normalizes the initialEntropy of the password generated based on the relative strength
     * of the password compared to the minimum and maximum possible entropy.
     *
     * @param initialEntropy the initialEntropy of the password generated
     * @return a normalized value between 0 and 1
     */
    public static double getNormalizedValue(double initialEntropy) {
        final double MIN_ENTROPY = 37.60351774512874; //Minimum possible entropy for a generated password
        final double MAX_ENTROPY = 419.4936865073688; //Maximum possible entropy for a generated password

        return (initialEntropy - MIN_ENTROPY)/(MAX_ENTROPY - MIN_ENTROPY);
    }
}
